[workspace]
resolver = "3"
members = ["lettuce", "hidden_r1cs", "digital_objects"]

[workspace.dependencies]
anyhow = "1"
rand = "0.9.2"
rand_chacha = "0.9.0"
log = "0.4.28"

lettuce = "0"

[patch.crates-io]
lettuce = { path = "./lettuce" }
